apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-app
          image: osama82/laravel-app:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              value: local
            - name: APP_DEBUG
              value: "true"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: laravel-db-secret
                  key: host
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: laravel-db-secret
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laravel-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-db-secret
                  key: password
