apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-mysql
  template:
    metadata:
      labels:
        app: laravel-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: example_app
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-mysql
spec:
  selector:
    app: laravel-mysql
  ports:
    - port: 3306
